package util;

public enum LeftChoosePanel {
	ReserveHotelView,Changemessage_JPanel,Changepassword_JPanel,ChooseOrderTypetoClient_JPanel,MyFootView,
	ClientCreditInfos_JPanel,MaintainHotelBasicInfoPanel,RoomInfo_JPanel,OrderPanelViewInHotelWorker,
	HotelStrategyPanel,CheckInPanel,CheckOutPanel,OfflineCheckIn_JPanel,ManageWebMarketManPanel,ManageCustomerPanel,
	ManageHotelWorkerPanel,OrderPanelInWebMarketMan,DepositPanel,Clientlevelrule_JPanel,Makewebstr_JPanel
}
